name: Deploy para Firebase Hosting

on:
  push:
    branches:
      - main  # Altere se sua branch principal tiver outro nome

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Fazer deploy para Firebase
        run: firebase deploy --token "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TESTE_62C36 }}"
